### ISSUE TITLE
TODO-List

### ISSUE THREAD

**Issue by Dassderdie** [Dassderdie/synchronized-sax-gandalf#3]
* [ ] Automatically determine whether the client is Leader or Follower (+ make sure there is always just one Leader!)
* [ ] Decouple Channel etc into extra component/Dialog
* [ ] Share a channel via link
* [ ] Error handling/messages
* [ ] Change the video-id etc. via Pusher
